export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};

export const userConstants = {
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
  CLEAR_REGISTER_STATE: 'CLEAR_REGISTER_STATE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};

export const expenseConstants = {
  GET_EXPENSES_REQUEST: 'GET_EXPENSES_REQUEST',
  GET_EXPENSES_SUCCESS: 'GET_EXPENSES_SUCCESS',
  GET_EXPENSES_FAILURE: 'GET_EXPENSES_FAILURE',

  DELETE_EXPENSE_BY_ID_REQUEST: 'DELETE_EXPENSE_BY_ID_REQUEST',
  DELETE_EXPENSE_BY_ID_SUCCESS: 'DELETE_EXPENSE_BY_ID_SUCCESS',
  DELETE_EXPENSE_BY_ID_FAILURE: 'DELETE_EXPENSE_BY_ID_FAILURE',

  UPDATE_EXPENSE_REQUEST: 'UPDATE_EXPENSE_REQUEST',
  UPDATE_EXPENSE_SUCCESS: 'UPDATE_EXPENSE_SUCCESS',
  UPDATE_EXPENSE_FAILURE: 'UPDATE_EXPENSE_FAILURE',

  ADD_EXPENSE_REQUEST: 'ADD_EXPENSE_REQUEST',
  ADD_EXPENSE_SUCCESS: 'ADD_EXPENSE_SUCCESS',
  ADD_EXPENSE_FAILURE: 'ADD_EXPENSE_FAILURE',

  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};

export const totalConstants = {
  GET_TOTAL_WEEK_REQUEST: 'GET_TOTAL_WEEK_REQUEST',
  GET_TOTAL_WEEK_SUCCESS: 'GET_TOTAL_WEEK_SUCCESS',
  GET_TOTAL_WEEK_FAILURE: 'GET_TOTAL_WEEK_FAILURE',

  GET_TOTAL_CATEGORY_REQUEST: 'GET_TOTAL_CATEGORY_REQUEST',
  GET_TOTAL_CATEGORY_SUCCESS: 'GET_TOTAL_CATEGORY_SUCCESS',
  GET_TOTAL_CATEGORY_FAILURE: 'GET_TOTAL_CATEGORY_FAILURE',

  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};
